  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: galaxy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"          # <-- ajout
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro   # <-- ajout (monte les certs en lecture seule)
    depends_on:
      - back
    networks:
      - galaxy-net