server {
    listen 80;
    server_name _;

    # Racine : les fichiers statiques du front
    root /usr/share/nginx/html;
    index index.html;

    # --- Routing de l'API vers le back Spring Boot ---
    location /api/ {
        # "back" = nom du service dans docker-compose, résolu par le DNS interne Docker
        proxy_pass http://back:8080;

        # Transmettre les vraies infos du client au back
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # CRUCIAL pour ton cookie Secure : dit à Spring qu'on est en HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- SPA : tout le reste renvoie index.html ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}